# Week 1, Fri, 4/4

In [2]:
def myadd(a, b = 1):
    return a + b

In [13]:
myadd(2,3)

5

In [14]:
myadd(2)

3

In [15]:
myadd(2,b=3)

5

In [16]:
import numpy as np

In [17]:
a = np.array([[1,2,3],[4,5,6]])

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
type(a)

numpy.ndarray

In [20]:
a.shape

(2, 3)

In [22]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
ones = np.ones((3,4))
ones


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
randint_arr = np.random.randint(0,10, size=(10,10))
randint_arr

array([[0, 9, 9, 7, 0, 4, 3, 8, 1, 1],
       [2, 1, 6, 4, 2, 5, 8, 6, 9, 9],
       [0, 9, 7, 2, 7, 8, 0, 9, 8, 9],
       [1, 1, 0, 7, 5, 8, 5, 7, 7, 3],
       [8, 8, 3, 3, 4, 3, 1, 9, 1, 6],
       [0, 9, 9, 2, 1, 7, 2, 7, 3, 6],
       [7, 2, 3, 6, 1, 3, 8, 1, 0, 3],
       [3, 3, 5, 8, 0, 2, 7, 7, 2, 0],
       [4, 7, 1, 9, 9, 7, 5, 0, 9, 7],
       [8, 3, 0, 4, 1, 9, 6, 2, 6, 7]])

In [29]:
matrix = np.random.rand(2, 3)
matrix

array([[0.6232891 , 0.15796073, 0.9216035 ],
       [0.21144622, 0.87990321, 0.97395649]])

In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a[0,1]

2

In [33]:
arr[0,:]

array([1, 2, 3])

In [34]:
arr[:,2]

array([3, 6, 9])

In [35]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [36]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [37]:
arr1 + arr2

array([5, 7, 9])

In [38]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [39]:
arr1 + 5

array([6, 7, 8])

In [40]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr.mean()

5.0

In [42]:
np.mean(arr)

5.0

In [43]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [47]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [69]:
matrix = np.random.rand(4, 3)
matrix

array([[0.33990371, 0.36885376, 0.04091363],
       [0.43764187, 0.24440322, 0.72463754],
       [0.45655341, 0.97565942, 0.56768338],
       [0.17534151, 0.07412288, 0.18285569]])

In [70]:
# A = max of min of each row
A = matrix.min(axis=1).max()

In [71]:
# B = min of max of each column
B = matrix.max(axis=0).min()

In [72]:
A<B

False

In [74]:
a = [3,2,1]

In [75]:
a.sort()

In [76]:
a

[1, 2, 3]

In [121]:
from math import sqrt
class Vector():
    dim = 2
    def __init__(self, input_x, input_y):
        self.x = input_x
        self.y = input_y

    def length(self):
        l = sqrt(self.x**2+self.y**2)
        return l
    def scale(self, c):
        self.x = self.x * c
        self.y = self.y * c
    def __pr__(self):
        return f'({self.x}, {self.y})'

    def add(self, other):
        x = self.x + other.x
        y = self.y + other.y
        return Vector(x,y)

    # def __add__(self, other):
    #     x = self.x + other.x
    #     y = self.y + other.y
    #     return Vector(x,y)
        

In [122]:
v = Vector(3,4)
print(v)

In [117]:
v = Vector(3,4)
w = Vector(1,2)
z = v.add(w)
print(z)

(4, 6)


In [118]:
print(v)

(3, 4)


In [115]:
v + w

(4, 6)