# Week 1, Fri, 4/4

In [2]:
def myadd(a, b = 1):
    return a + b

In [3]:
myadd(2,3)

5

In [4]:
myadd(2)

3

In [5]:
myadd(2,b=3)

5

In [6]:
import numpy as np

In [7]:
a = np.array([[1,2,3],[4,5,6]])

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(a)

numpy.ndarray

In [10]:
a.shape

(2, 3)

In [11]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
ones = np.ones((3,4))
ones


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
randint_arr = np.random.randint(0,10, size=(10,10))
randint_arr

array([[4, 8, 9, 4, 3, 4, 3, 7, 7, 4],
       [1, 6, 0, 7, 4, 5, 1, 7, 8, 5],
       [7, 1, 6, 8, 0, 2, 8, 9, 5, 9],
       [3, 2, 7, 3, 4, 5, 9, 2, 2, 0],
       [8, 2, 2, 8, 1, 4, 4, 2, 3, 5],
       [7, 8, 6, 2, 9, 9, 2, 5, 1, 7],
       [7, 8, 0, 7, 0, 9, 2, 8, 7, 9],
       [5, 8, 3, 9, 5, 8, 7, 7, 6, 4],
       [4, 8, 5, 8, 8, 9, 2, 0, 8, 6],
       [6, 4, 3, 7, 6, 4, 5, 7, 0, 8]])

In [14]:
matrix = np.random.rand(2, 3)
matrix

array([[0.37706141, 0.35093829, 0.98766998],
       [0.39305966, 0.45541896, 0.94713432]])

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a[0,1]

2

In [18]:
arr[0,:]

array([1, 2, 3])

In [19]:
arr[:,2]

array([3, 6, 9])

In [20]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [22]:
arr1 + arr2

array([5, 7, 9])

In [23]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [24]:
arr1 + 5

array([6, 7, 8])

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.mean()

5.0

In [27]:
np.mean(arr)

5.0

In [28]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [29]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [67]:
matrix = np.random.rand(4, 3)
matrix

array([[0.52803506, 0.52758081, 0.53961703],
       [0.76559197, 0.55888227, 0.37093139],
       [0.00519933, 0.40982572, 0.70160406],
       [0.93246644, 0.17441707, 0.63842241]])

In [68]:
# A = max of min of each row
A = matrix.min(axis=1).max()
print(A)

0.5275808084576713


In [69]:
# B = min of max of each column
B = matrix.max(axis=0).min()
print(B)

0.558882270998096


In [70]:
A<=B

True

In [ ]:
a = [3,2,1]

In [36]:
a.sort()

In [37]:
a

[1, 2, 3]

In [38]:
from math import sqrt
class Vector():
    dim = 2
    def __init__(self, input_x, input_y):
        self.x = input_x
        self.y = input_y

    def length(self):
        l = sqrt(self.x**2+self.y**2)
        return l
    def scale(self, c):
        self.x = self.x * c
        self.y = self.y * c
    def __pr__(self):
        return f'({self.x}, {self.y})'

    def add(self, other):
        x = self.x + other.x
        y = self.y + other.y
        return Vector(x,y)

    # def __add__(self, other):
    #     x = self.x + other.x
    #     y = self.y + other.y
    #     return Vector(x,y)
        

In [39]:
v = Vector(3,4)
print(v)

In [40]:
v = Vector(3,4)
w = Vector(1,2)
z = v.add(w)
print(z)

In [41]:
print(v)

In [42]:
v + w

TypeError: unsupported operand type(s) for +: 'Vector' and 'Vector'